### ISSUE TITLE
Support SGP30 over I2C

### ISSUE THREAD

**Issue by 0x46616c6b** [periph/devices#32]
**What kind of new feature are you looking for?**

- Hardware: [SGP30](https://shop.pimoroni.com/products/sgp30-air-quality-sensor-breakout)

I implemented in this [repository](https://github.com/0x46616c6b/airquality-exporter/blob/main/devices/sgp30/sgp30.go) the SGP30 already and want to ask if I can contribute this piece of code. It is fully functional but I did not implemented the CRC checks which are mentioned in the datasheet.

**Do you plan to:**
- Contribute an initial driver: Yes
- Write unit tests: No
- Update https://github.com/periph/cmd to use the new functionality: Yes

**Comment by maruel** [comment]
It looks great! The only nit would be to not export the commands. Thanks!
